# Generated by Django 5.0.6 on 2024-05-26 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='due_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carinstance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.profile'),
        ),
    ]
