# Generated by Django 5.0.6 on 2024-05-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_carinstance_due_start_carinstance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinstance',
            name='user',
        ),
        migrations.AddField(
            model_name='carinstance',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.carinstance'),
        ),
    ]
