# Generated by Django 5.0.6 on 2024-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_carinstance_user_carinstance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
