# Generated by Django 5.0.6 on 2024-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_carinstance_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinstance',
            name='number',
            field=models.CharField(blank=True, help_text='Номер заказа', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
