# Generated by Django 5.0.6 on 2024-05-27 16:55

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_carinstance_number_alter_carinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinstance',
            name='number',
            field=models.CharField(default=catalog.models.generate_order_number, help_text='Номер заказа', max_length=10, unique=True),
        ),
    ]
